routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {

	Route::resource('clientes', 'ClientesController');
	Route::resource('produtos', 'ProdutosController');
	Route::resource('pedidos', 'PedidosController');

});

Route::get('/trocar-linguagem/{locale}', ['as' => 'trocarlinguagem', 'uses' => 'HomeController@trocarLinguagem']);

resources/views/layouts/app.blade.php
@include('layouts.header')
    @include('layouts.menu')
    
        @yield('content')

@include('layouts.footer')

resources/views/layouts/footer.blade.php
        </div>
        <footer>
            <!-- Scripts -->
            <script src="{{ asset('js/app.js') }}"></script>
            <script src="{{ asset('js/datatables.js') }}"></script>
            <script type="text/javascript">
                var intialize_datatable = {
                        "dom"     : 'ltip',
                        "lengthMenu"    : [[20, 50, -1], [20, 50, "All"]],
                    },
                language_pt = "{{ session('locale') == 'pt-br' ? true : false}}";

                if(language_pt){
                    intialize_datatable.language = {
                        "url":"{{ asset('js/Portuguese-Brasil.json') }}"
                    };
                }
            </script>
            <script src="{{ asset('js/jquery.mask.js') }}"></script>
            <script src="{{ asset('js/default.js') }}"></script>
        </footer>
    </body>
</html>

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link href="{{ asset('css/datatables.css') }}" rel="stylesheet">
    <link href="{{ asset('css/default.css') }}" rel="stylesheet">

</head>
<body>

resources/views/layouts/menu.blade.php
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/home') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        <li><a href="{{route('produtos.index')}}">{{ trans('messages.Products') }}</a></li>
                        <li><a href="{{route('clientes.index')}}">{{ trans('messages.Clients') }}</a></li>
                        <li><a href="{{route('pedidos.index')}}">{{ trans('messages.Orders') }}</a></li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">{{ trans('auth.Register')}}</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ trans('messages.Languages')}} <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                    @foreach(config('app.languages') as $lang)
                                       <li class="{{ session('locale') == $lang ? 'active' : '' }}">
                                            <a href="{{ route('trocarlinguagem', ['locale'=>$lang]) }}" >{{ $lang }}</a>
                                       </li>
                                    @endforeach
                                  </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            {{ trans('auth.Logout') }}
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="container">
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif